# Generated by Django 5.0.4 on 2024-05-07 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_website', '0003_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='quote',
            new_name='message',
        ),
    ]
