# Generated by Django 5.0.4 on 2024-05-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_website', '0004_rename_quote_testimonial_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprocess',
            name='template',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
