# Generated by Django 5.0.4 on 2024-05-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_website', '0005_serviceprocess_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprocess',
            name='template',
        ),
        migrations.AddField(
            model_name='service',
            name='template',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
