# Generated by Django 5.0.4 on 2024-05-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_website', '0006_remove_serviceprocess_template_service_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='template',
            field=models.CharField(max_length=50),
        ),
    ]
