# Generated by Django 5.0.4 on 2024-05-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_website', '0008_alter_service_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='template',
            field=models.CharField(choices=[('obrezovanje-dreves', 'Obrezovanje dreves'), ('podiranje-dreves', 'Podiranje dreves'), ('obrezovanje-zive-meje', 'Obrezovanje žive meje')], max_length=100),
        ),
    ]
