# Generated by Django 5.0.4 on 2024-06-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_website', '0009_alter_service_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceprocess',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='serviceprocess',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
